export const GAME_ACTION_TYPES = {
    SET_GAME_OVER: "SET_GAME_OVER",
    SET_LOADING: "SET_LOADING",
    SET_HAS_WON: "SET_HAS_WON",
    SET_SOLUTION: "SET_SOLUTION",
    SET_ROWS: "SET_ROWS",
    SET_ACTIVE_ROW: "SET_ACTIVE_ROW",
    SET_KEY_COLORS: "SET_KEY_COLORS",
    RESET_BOARD: "RESET_BOARD",
    INCREMENT_TIMER: "INCREMENT_TIMER",
    RESET_TIMER: "RESET_TIMER",
    PAUSE_TIMER: "PAUSE_TIMER",
    RESUME_TIMER: "RESUME_TIMER",
    SET_CHALLENGE_ID: "SET_CHALLENGE_ID"
};
