export const OPTION_ACTION_TYPES = {
    SET_WORD_LENGTH: "SET_WORD_LENGTH",
    SET_NUM_GUESSES: "SET_NUM_GUESSES",
    SET_HARD_MODE: "SET_HARD_MODE",
    SET_TIME_TRIAL: "SET_TIME_TRIAL",
    SET_TIME_NUM_WORDS: "SET_TIME_NUM_WORDS",
};
